### ISSUE TITLE
sqlite3.OperationalError: no such table: bossoidc_keycloak

### ISSUE THREAD

**Issue by jonalv** [jhuapl-boss/boss-oidc#1]
I have been following the instructions here and at http://blog.jonharrington.org/static/integrate-django-with-keycloak/. One I have logged in on Keycloak and I get the redirect back to my Django app my Django app complains about no table bossoidc_keycloak:

App 62 stderr: ERROR Internal Server Error: /openid/callback/login/
App 62 stderr: Traceback (most recent call last):
App 62 stderr:   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 65, in execute
App 62 stderr:     return self.cursor.execute(sql, params)
App 62 stderr:   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/sqlite3/base.py", line 328, in execute
App 62 stderr:     return Database.Cursor.execute(self, query, params)
App 62 stderr: sqlite3.OperationalError: no such table: bossoidc_keycloak

This confuses me for two reason, firstly because I am quite sure that I have done the migrations and secondly because the features list says "No models stored in database - just some configuration in settings.py to keep it simple". What's going on here and what could I be doing wrong?

**Comment by derek-pryor** [comment]
This is because we've not been keeping the documentation up to date. We added a model to bossoidc to track the Keycloak user id so that we could accurately tell if a user account was deleted.

If you run `python manage.py makemigrations bossoidc` and then `python manage.py migrate` it should create the needed table.

I will update the instructions later today to fix this oversight.
