### ISSUE TITLE
Can coexist boss-oidc with Django facebook?

### ISSUE THREAD

**Issue by Allan-Nava** [jhuapl-boss/boss-oidc#8]
Hi @derek-pryor ,

I have enabled the social login in keycloak but I need to handle the Facebook funcionality with the keycloak user in django

**Comment by derek-pryor** [comment]
@Allan-Nava I am unsure if/how that would work as that is not a deployment scenario that we have tested. Feel free to test and if you discover a bug or that boss-oidc is hardcoded in such a way to not allow this open an issue or pull request.

Since this doesn't reference a bug with the boss-oidc plugin I am closing the issue.
